name: Deploy Edge Functions

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/functions/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy All Edge Functions
        run: |
          echo "🚀 Deploying all Edge Functions..."
          
          # Lista todas as pastas dentro de supabase/functions
          for function_dir in supabase/functions/*/; do
            if [ -d "$function_dir" ]; then
              function_name=$(basename "$function_dir")
              echo "📦 Deploying function: $function_name"
              
              # Deploy da função
              supabase functions deploy "$function_name" \
                --project-ref ${{ secrets.SUPABASE_PROJECT_REF }} \
                --no-verify-jwt false
              
              if [ $? -eq 0 ]; then
                echo "✅ $function_name deployed successfully!"
              else
                echo "❌ Failed to deploy $function_name"
                exit 1
              fi
            fi
          done
          
          echo "🎉 All Edge Functions deployed successfully!"
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deployment Summary
        run: |
          echo "📊 Deployment Summary:"
          echo "- Project: ${{ secrets.SUPABASE_PROJECT_REF }}"
          echo "- Branch: ${{ github.ref_name }}"
          echo "- Commit: ${{ github.sha }}"
          echo "- Functions deployed: $(ls -d supabase/functions/*/ | wc -l)"
