CREATE TABLE `calculated_metrics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`simulationParamsId` int NOT NULL,
	`scenario` enum('3M','4M','5M') NOT NULL,
	`period` enum('daily','weekly','monthly') NOT NULL,
	`week` int,
	`day` int,
	`requiredViews` int NOT NULL,
	`requiredLeads` int NOT NULL,
	`requiredClicks` int NOT NULL,
	`trafficInvestment` text NOT NULL,
	`expectedRevenue` text NOT NULL,
	`roi` text NOT NULL,
	`roas` text NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `calculated_metrics_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `daily_results` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`date` timestamp NOT NULL,
	`scenario` enum('3M','4M','5M') NOT NULL,
	`week` int NOT NULL,
	`marketingDirectSales` int NOT NULL DEFAULT 0,
	`commercialSales` int NOT NULL DEFAULT 0,
	`marketingDirectRevenue` text NOT NULL DEFAULT ('0.00'),
	`commercialRevenue` text NOT NULL DEFAULT ('0.00'),
	`actualViews` int DEFAULT 0,
	`actualLeads` int DEFAULT 0,
	`actualInvestment` text DEFAULT ('0.00'),
	`actualCPA` text DEFAULT ('0.00'),
	`actualCPL` text DEFAULT ('0.00'),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `daily_results_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `simulation_params` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`scenario` enum('3M','4M','5M') NOT NULL,
	`vslConversionRate` text NOT NULL DEFAULT ('1.50'),
	`tslConversionRate` text NOT NULL DEFAULT ('1.50'),
	`checkoutConversionRate` text NOT NULL DEFAULT ('80.00'),
	`upsellConversionRate` text NOT NULL DEFAULT ('25.00'),
	`sdrConversionRate` text NOT NULL DEFAULT ('20.00'),
	`targetCPA` text NOT NULL DEFAULT ('450.00'),
	`targetCPL` text NOT NULL DEFAULT ('30.00'),
	`avgCTR` text NOT NULL DEFAULT ('3.00'),
	`frontTicket` text NOT NULL DEFAULT ('797.00'),
	`upsellTicket` text NOT NULL DEFAULT ('247.00'),
	`avgTicket` text NOT NULL DEFAULT ('1000.00'),
	`sdrDailyMeetings` int NOT NULL DEFAULT 4,
	`sdrCount` int NOT NULL DEFAULT 1,
	`closerCount` int NOT NULL DEFAULT 2,
	`isActive` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `simulation_params_id` PRIMARY KEY(`id`)
);
