-- Migration: Create internal pages table
-- Date: 2026-01-10

CREATE TABLE IF NOT EXISTS pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    html_content TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for fast lookup by slug
CREATE INDEX IF NOT EXISTS pages_slug_idx ON pages (slug);

-- RLS Policies
ALTER TABLE pages ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to manage pages
CREATE POLICY "Enable read access for authenticated users" ON pages FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Enable insert access for authenticated users" ON pages FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Enable update access for authenticated users" ON pages FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Enable delete access for authenticated users" ON pages FOR DELETE USING (auth.role() = 'authenticated');

-- Allow public read access (via Worker) - service role will bypass RLS anyway, 
-- but we might want anon access if we ever fetch from client directly.
-- For now, Worker uses service role, so this is optional but good practice for "active" pages if we add a status column later.
-- Keeping it restricted to auth/service_role for now to avoid leaking raw data.

-- Notify schema reload
NOTIFY pgrst, 'reload schema';
